export const constants = {
    services: {
        ad: "বিজ্ঞাপন",
        applianceRepair: "অ্যাপ্লায়েন্স মেরামত",
        broadband: "ব্রডব্যান্ড",
        building: "বিল্ডিং",
        carRent: "গাড়ি ভাড়া",
        carpenter: "কার্পেন্টার",
        cleaner: "ক্লিনার",
        cleaning: "ক্লিনিং সার্ভিস",
        dance: "ডান্স টিউটর",
        doctor: "ডাক্তার",
        dokan: "দোকান",
        electrician: "ইলেকট্রিশিয়ান",
        electronics: "ইলেকট্রনিক্স মেরামত",
        grocery: "গ্রোসারি",
        homeTutor: "হোম টিউটর",
        job: "চাকরি",
        kitchen: "কিচেন",
        labTests: "ল্যাব টেস্টস",
        makeUp: "মেকআপ আর্টিস্ট",
        medicine: "মেডিসিন ডেলিভারি",
        moving: "মুভিং সার্ভিস",
        music: "মিউজিক টিউটর",
        nurse: "নার্স",
        painter: "পেইন্টার",
        pestControl: "পেস্ট কন্ট্রোল",
        pharmacy: "ফার্মেসি",
        physiotherapist: "ফিজিওথেরাপিস্ট",
        plumber: "প্লাম্বার",
        property: "প্রপার্টি",
        salonAtHome: "সেলুন অ্যাট হোম",
        totoVara: "টোটো ভাড়া",
        tutor: "টিউটর"
    },
    servicesIcons: {
        ad: "megaphone-outline",
        applianceRepair: "construct-outline",
        broadband: "wifi-outline",
        building: "business-outline",
        carRent: "car-outline",
        carpenter: "hammer-outline",
        cleaner: "person-outline",              // can replace with "sparkles-outline" if using v7+
        cleaning: "sparkles-outline",
        dance: "musical-notes-outline",
        doctor: "medkit-outline",
        dokan: "storefront-outline",
        electrician: "flash-outline",
        electronics: "hammer-outline",
        grocery: "basket-outline",
        homeTutor: "school-outline",
        job: "briefcase-outline",
        kitchen: "restaurant-outline",
        labTests: "flask-outline",
        makeUp: "color-palette-outline",
        medicine: "medkit-outline",
        moving: "cube-outline",
        music: "musical-notes-outline",
        nurse: "bandage-outline",
        painter: "color-fill-outline",
        pestControl: "bug-outline",
        pharmacy: "medkit-outline",
        physiotherapist: "fitness-outline",     // stretching context
        plumber: "water-outline",
        property: "home-outline",
        salonAtHome: "cut-outline",
        totoVara: "bus-outline",                // closest vehicle icon; can replace later
        tutor: "school-outline"
    }
}